{
 "title": "Surveys Prod ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Surveys Por Mercado",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "helpsurveydbprod",
     "rawSql": "SELECT TOP(50) location, COUNT(ticketId) FROM helpsurveydbprod.dbo.survey GROUP BY location "
    }
   ]
  },
  {
   "title": "Estatus Surveys",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "helpsurveydbprod",
     "rawSql": "-- TOTAL DE SURVEYS POR ESTADO EN EL DÍA ACTUAL\r\n\r\n-- Total de surveys no contestadas\r\nDECLARE  @TotalSurveys INT;\r\nSELECT\t @TotalSurveys = COUNT(*) \r\nFROM\t survey\r\n--WHERE\t CONVERT(DATE, [updatedAt]) = CONVERT(DATE, GETDATE())\r\n;\r\n\r\n-- Total de surveys no contestadas\r\nDECLARE  @TotalUnansweredSurveys INT;\r\nSELECT\t @TotalUnansweredSurveys = COUNT(*) \r\nFROM\t survey\r\nWHERE\t status != 'completed'\r\n--AND\t\t CONVERT(DATE, [updatedAt]) = CONVERT(DATE, GETDATE())\r\n;\r\n\r\nSELECT\t status AS 'Survey Status',\r\n\t\t COUNT(*) AS Total,\r\n\t\t CONCAT(CAST(ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 0) AS INT),'%') AS Porcentaje\r\nFROM\t survey\r\n--WHERE\t CONVERT(DATE, [updatedAt]) = CONVERT(DATE, GETDATE())\r\nGROUP BY status\r\n\r\nUNION ALL\r\n\r\nSELECT\t 'Total unanswered surveys' AS 'Survey Status',\r\n\t\t @TotalUnansweredSurveys AS Total,\r\n\t\t CONCAT(CAST(ROUND(100.0 * @TotalUnansweredSurveys / @TotalSurveys, 0) AS INT), '%') AS Porcentaje\r\n\t \r\nUNION ALL\r\n\r\nSELECT\t 'Total surveys' AS 'Survey Status',\r\n\t\t @TotalSurveys AS Total,\r\n\t\t '100%' AS Porcentaje \r\n\r\nORDER BY Total asc"
    }
   ]
  },
  {
   "title": "Estatus Tickets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "helpsurveydbprod",
     "rawSql": "SELECT\t status,\r\n   \t\t COUNT(*) AS TotalPorEstatus,\r\n  \t\t CONCAT(CAST(ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 0) AS INT),'%') AS PorcentajePorEstatus\r\nFROM\t ticket\r\nGROUP BY status\r\nUNION ALL\r\nSELECT\t 'Total'  AS status,\r\n   \t\t COUNT(*) AS TotalPorEstatus,\r\n  \t\t '100%'   AS PorcentajePorEstatus\r\nFROM     ticket\r\nORDER BY TotalPorEstatus asc"
    }
   ]
  },
  {
   "title": "Estatus encuestas -Tabla",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "helpsurveydbprod",
     "rawSql": "-- TOTAL DE SURVEYS POR ESTADO EN EL DÍA ACTUAL\r\n\r\n-- Total de surveys no contestadas\r\nDECLARE  @TotalSurveys INT;\r\nSELECT\t @TotalSurveys = COUNT(*) \r\nFROM\t survey\r\n--WHERE\t CONVERT(DATE, [updatedAt]) = CONVERT(DATE, GETDATE())\r\n;\r\n\r\n-- Total de surveys no contestadas\r\nDECLARE  @TotalUnansweredSurveys INT;\r\nSELECT\t @TotalUnansweredSurveys = COUNT(*) \r\nFROM\t survey\r\nWHERE\t status != 'completed'\r\n--AND\t\t CONVERT(DATE, [updatedAt]) = CONVERT(DATE, GETDATE())\r\n;\r\n\r\nSELECT\t status AS 'Survey Status',\r\n\t\t COUNT(*) AS Total,\r\n\t\t CONCAT(CAST(ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 0) AS INT),'%') AS Porcentaje\r\nFROM\t survey\r\n--WHERE\t CONVERT(DATE, [updatedAt]) = CONVERT(DATE, GETDATE())\r\nGROUP BY status\r\n\r\nUNION ALL\r\n\r\nSELECT\t 'Total unanswered surveys' AS 'Survey Status',\r\n\t\t @TotalUnansweredSurveys AS Total,\r\n\t\t CONCAT(CAST(ROUND(100.0 * @TotalUnansweredSurveys / @TotalSurveys, 0) AS INT), '%') AS Porcentaje\r\n\t \r\nUNION ALL\r\n\r\nSELECT\t 'Total surveys' AS 'Survey Status',\r\n\t\t @TotalSurveys AS Total,\r\n\t\t '100%' AS Porcentaje \r\n\r\nORDER BY Total asc"
    }
   ]
  },
  {
   "title": "Estatus Tickets - Tabla",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dataset": "helpsurveydbprod",
     "rawSql": "SELECT\t status,\r\n   \t\t COUNT(*) AS TotalPorEstatus,\r\n  \t\t CONCAT(CAST(ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 0) AS INT),'%') AS PorcentajePorEstatus\r\nFROM\t ticket\r\nGROUP BY status\r\nUNION ALL\r\nSELECT\t 'Total'  AS status,\r\n   \t\t COUNT(*) AS TotalPorEstatus,\r\n  \t\t '100%'   AS PorcentajePorEstatus\r\nFROM     ticket\r\nORDER BY TotalPorEstatus asc"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "helpsurveydbprod",
     "rawSql": "SELECT  ticketId, [dbo].[ticket].[user], assignedTo, title, impact, urgency, priority, helpCreatedAt FROM helpsurveydbprod.dbo.ticket ORDER BY helpCreatedAt "
    }
   ]
  },
  {
   "title": "Tickets por Locacion ",
   "type": "bargauge",
   "gridPos": { "h": 35, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "helpsurveydbprod",
     "rawSql": "SELECT TOP(50) location, COUNT(ticketId) FROM helpsurveydbprod.dbo.ticket GROUP BY location "
    }
   ]
  }
 ]
}